export enum McpToolName {
  GetViewer = "linear_getViewer",
  GetOrganization = "linear_getOrganization",
  GetUsers = "linear_getUsers",
  GetLabels = "linear_getLabels",
  GetTeams = "linear_getTeams",
  GetWorkflowStates = "linear_getWorkflowStates",
  GetProjects = "linear_getProjects",
  CreateProject = "linear_createProject",
  UpdateProject = "linear_updateProject",
  AddIssueToProject = "linear_addIssueToProject",
  GetProjectIssues = "linear_getProjectIssues",
  GetCycles = "linear_getCycles",
  GetActiveCycle = "linear_getActiveCycle",
  AddIssueToCycle = "linear_addIssueToCycle",
  GetIssues = "linear_getIssues",
  GetIssueById = "linear_getIssueById",
  SearchIssues = "linear_searchIssues",
  CreateIssue = "linear_createIssue",
  UpdateIssue = "linear_updateIssue",
  CreateComment = "linear_createComment",
  AddIssueLabel = "linear_addIssueLabel",
  RemoveIssueLabel = "linear_removeIssueLabel",
  AssignIssue = "linear_assignIssue",
  SubscribeToIssue = "linear_subscribeToIssue",
  ConvertIssueToSubtask = "linear_convertIssueToSubtask",
  CreateIssueRelation = "linear_createIssueRelation",
  ArchiveIssue = "linear_archiveIssue",
  SetIssuePriority = "linear_setIssuePriority",
  TransferIssue = "linear_transferIssue",
  DuplicateIssue = "linear_duplicateIssue",
  GetIssueHistory = "linear_getIssueHistory",
  GetComments = "linear_getComments",
}

export enum LinearPriority {
  URGENT = 1,
  HIGH = 2,
  NORMAL = 3,
  LOW = 4,
}

export enum LinearStates {
  Backlog = "Backlog",
  Todo = "Todo",
  InProgress = "In Progress",
  InReview = "In Review",
  NeedsQA = "Needs QA",
  Done = "Done",
  Canceled = "Canceled",
  Triage = "Triage",
}
